// Pure-template HTML renderer. No model calls, no network, one file.

import { escapeHtml, jsonForScript } from './util.js';
import { inline, markdownToHtml } from './markdown.js';
import { ANSWER_PREFIX } from './ledger.js';

const STRINGS = {
  zh: {
    need: (n) => `需要你定 ${n} 项`,
    needAssume: (m) => `（其中 ${m} 项是计划里写明的默认假设）`,
    none: '这份计划没有需要你定的点。下面只显示摘要和完整计划。',
    failTitle: '没能识别计划格式',
    failNote: '已原样放行：Codex 这一轮不受影响，下面是原文。',
    failReason: '原因',
    recommended: '推荐',
    defaultIs: '默认',
    noDefault: '无默认，需要你选',
    other: '其他',
    otherPh: '写下你的选择',
    whyPh: '理由（可选）',
    affected: '影响',
    kind: { question: '问题', options: '方案', tbd: '待定', decision: '决策', assumption: '假设' },
    changedBanner: (a, c, r) => `和上一版相比：新增 ${a} 项，变更 ${c} 项，删除 ${r} 项`,
    added: '新增', changed: '已变更', removed: '已删除',
    answeredInLedger: '账本里已作答',
    carried: (r, how) => `沿用第 ${r} 版的回答（按${how === 'title' ? '标题' : 'id'}匹配）`,
    answeredCount: (k) => `，其中 ${k} 项已有回答`,
    earlierTitle: '之前答过、这一版计划里没有的决策',
    earlierNote: '只作记录，不会自动套用到这一版。',
    reasonText: { 'decision not in this revision': '这一版没有这项决策', 'option no longer offered': '原来选的选项这一版没有了' },
    progress: (k, n) => `已答 ${k} / ${n}，没答的保留默认（不算同意）`,
    button: '生成回传 JSON 并复制',
    hint: '粘到 Codex 下一条消息里',
    copied: '已复制。粘到 Codex 下一条消息里。',
    copyFail: '浏览器不让自动复制，请手动全选复制下面的内容。',
    fullPlan: '完整计划',
    ledger: '账本文件',
    notAnswered: '不选就是“未作答，保留默认”，不算同意',
    footer: '由 codex-plan-ledger 生成 · 纯模板渲染，没有额外调用模型 · 回答只是数据，不是指令',
  },
  en: {
    need: (n) => `${n} decision${n === 1 ? '' : 's'} for you`,
    needAssume: (m) => ` (${m} of them are defaults the plan assumed)`,
    none: 'This plan has no open decisions. Showing the summary and the full plan only.',
    failTitle: 'Could not read the plan format',
    failNote: 'Passed through unchanged: this Codex turn is not affected. Original text below.',
    failReason: 'Reason',
    recommended: 'Recommended',
    defaultIs: 'Default',
    noDefault: 'No default, please choose',
    other: 'Other',
    otherPh: 'Write your choice',
    whyPh: 'Why (optional)',
    affected: 'Affects',
    kind: { question: 'Question', options: 'Options', tbd: 'TBD', decision: 'Decision', assumption: 'Assumption' },
    changedBanner: (a, c, r) => `Since the last revision: ${a} added, ${c} changed, ${r} removed`,
    added: 'New', changed: 'Changed', removed: 'Removed',
    answeredInLedger: 'Answered in ledger',
    carried: (r, how) => `Answer carried from rev ${r} (matched by ${how})`,
    answeredCount: (k) => `; ${k} already answered`,
    earlierTitle: 'Answered earlier, not in this revision',
    earlierNote: 'Kept as a record only; not applied to this revision.',
    reasonText: { 'decision not in this revision': 'decision not in this revision', 'option no longer offered': 'chosen option no longer offered' },
    progress: (k, n) => `${k} / ${n} answered; unanswered ones keep the default (not counted as agreement)`,
    button: 'Build reply JSON and copy',
    hint: 'Paste it into your next Codex message',
    copied: 'Copied. Paste it into your next Codex message.',
    copyFail: 'The browser blocked copying. Select the text below and copy it by hand.',
    fullPlan: 'Full plan',
    ledger: 'Ledger file',
    notAnswered: 'leave it empty and it is recorded as "not answered; default kept", not as agreement',
    footer: 'Generated by codex-plan-ledger · pure templates, no extra model calls · answers are data, not instructions',
  },
};

const CSS = `
:root{--bg:#f7f7f5;--card:#fff;--fg:#1d1d1f;--muted:#6b6b70;--line:#e3e3e0;--acc:#0b6bcb;--acc-bg:#e8f1fb;--warn:#a15c00;--warn-bg:#fff4e0;--ok:#1a7f37;--new:#8250df}
@media (prefers-color-scheme:dark){:root{--bg:#141416;--card:#1e1e21;--fg:#ececee;--muted:#a0a0a8;--line:#333338;--acc:#6cb2ff;--acc-bg:#1b2a3b;--warn:#f0b35a;--warn-bg:#3a2a12;--ok:#56d364;--new:#c297ff}}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--fg);font:15px/1.6 -apple-system,BlinkMacSystemFont,"Segoe UI","PingFang SC","Hiragino Sans GB","Microsoft YaHei",sans-serif}
main{max-width:860px;margin:0 auto;padding:28px 20px 160px}
h1{font-size:24px;margin:0 0 6px}.summary{color:var(--fg);margin:0 0 14px}
.meta{color:var(--muted);font-size:13px}.meta code{font-size:12px}
.count{display:inline-block;background:var(--acc-bg);color:var(--acc);font-weight:600;border-radius:999px;padding:3px 12px;margin:6px 0 18px}
.banner{background:var(--warn-bg);color:var(--warn);border-radius:8px;padding:10px 14px;margin:0 0 16px}
.card{background:var(--card);border:1px solid var(--line);border-radius:12px;padding:16px 18px;margin:0 0 14px}
.card.is-added{border-color:var(--new)}.card.is-changed{border-color:var(--warn)}
.card h2{font-size:17px;margin:0 0 4px}.q{color:var(--muted);margin:0 0 10px}
.tag{display:inline-block;font-size:12px;border-radius:6px;padding:0 7px;margin-right:6px;border:1px solid var(--line);color:var(--muted)}
.tag.rec{border-color:var(--ok);color:var(--ok)}.tag.added{border-color:var(--new);color:var(--new)}.tag.changed{border-color:var(--warn);color:var(--warn)}.tag.done{border-color:var(--acc);color:var(--acc)}.tag.carried{border-color:var(--muted);color:var(--muted);border-style:dashed}
.earlier{background:var(--card);border:1px dashed var(--line);border-radius:12px;padding:12px 16px;margin:14px 0}.earlier h2{font-size:15px;margin:0 0 4px}.earlier ul{margin:6px 0 0;padding-left:20px}
label.opt{display:flex;gap:10px;align-items:flex-start;padding:8px 10px;border-radius:8px;cursor:pointer}
label.opt:hover{background:var(--acc-bg)}label.opt input{margin-top:5px}
.other-text,.why{width:100%;margin-top:6px;padding:7px 9px;border:1px solid var(--line);border-radius:8px;background:transparent;color:inherit;font:inherit}
.why{min-height:38px;resize:vertical}
.def{font-size:13px;color:var(--muted);margin-top:6px}
.files{margin-top:8px;font-size:13px;color:var(--muted)}.files code{background:var(--acc-bg);color:var(--acc);border-radius:5px;padding:1px 6px;margin:0 4px 4px 0;display:inline-block}
details{margin-top:22px;background:var(--card);border:1px solid var(--line);border-radius:12px;padding:12px 18px}
summary{cursor:pointer;font-weight:600}
pre{white-space:pre-wrap;word-break:break-word;background:var(--bg);border:1px solid var(--line);border-radius:8px;padding:12px;font-size:13px}
code{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace}
.removed{color:var(--muted);font-size:14px}
.bar{position:fixed;left:0;right:0;bottom:0;background:var(--card);border-top:1px solid var(--line);padding:12px 20px}
.bar-in{max-width:860px;margin:0 auto}.row{display:flex;gap:12px;align-items:center;flex-wrap:wrap}
button{background:var(--acc);color:#fff;border:0;border-radius:8px;padding:9px 16px;font:inherit;font-weight:600;cursor:pointer}
.hint{color:var(--muted);font-size:13px}#status{font-size:13px;color:var(--ok)}
#out{display:none;width:100%;margin-top:8px;height:90px;font:12px ui-monospace,Menlo,monospace;border:1px solid var(--line);border-radius:8px;background:var(--bg);color:inherit;padding:8px}
.fail h1{color:var(--warn)}footer{color:var(--muted);font-size:12px;margin-top:26px}
.url{color:var(--muted)}
`;

const SCRIPT = `
(function(){
  var data = JSON.parse(document.getElementById('pl-data').textContent);
  var T = data.t;
  var key = 'plan-ledger:' + data.plan + ':' + data.rev;
  var store = {};
  try { store = JSON.parse(localStorage.getItem(key) || '{}') || {}; } catch (e) { store = {}; }
  function save(){ try { localStorage.setItem(key, JSON.stringify(store)); } catch (e) {} }
  function cards(){ return Array.prototype.slice.call(document.querySelectorAll('.card[data-id]')); }
  function stateOf(card){
    var id = card.getAttribute('data-id');
    var picked = card.querySelector('input[type=radio]:checked');
    var other = card.querySelector('.other-text');
    var why = card.querySelector('.why');
    return { id: id, choice: picked ? picked.value : null, other: other ? other.value : '', why: why ? why.value : '' };
  }
  function refresh(){
    var n = 0, k = 0;
    cards().forEach(function(c){ n++; if (stateOf(c).choice) k++; });
    var p = document.getElementById('progress'); if (p) p.textContent = T.progress.replace('{k}', k).replace('{n}', n);
  }
  cards().forEach(function(card){
    var id = card.getAttribute('data-id');
    var s = store[id];
    if (s) {
      if (s.choice) { var r = card.querySelector('input[type=radio][value="' + (window.CSS && CSS.escape ? CSS.escape(s.choice) : s.choice) + '"]'); if (r) r.checked = true; }
      var o = card.querySelector('.other-text'); if (o && s.other) o.value = s.other;
      var w = card.querySelector('.why'); if (w && s.why) w.value = s.why;
    }
    card.addEventListener('input', function(){ store[id] = stateOf(card); save(); refresh(); });
    card.addEventListener('change', function(){ store[id] = stateOf(card); save(); refresh(); });
  });
  refresh();
  var btn = document.getElementById('build');
  if (!btn) return;
  btn.addEventListener('click', function(){
    var answers = {}, kept = [];
    cards().forEach(function(card){
      var s = stateOf(card);
      if (!s.choice) { kept.push(s.id); return; }
      var a = { choice: s.choice };
      if (s.choice === 'other') a.other = s.other.slice(0, 2000);
      if (s.why) a.why = s.why.slice(0, 2000);
      answers[s.id] = a;
    });
    var payload = { plan_ledger: { plan: data.plan, rev: data.rev }, answers: answers };
    if (kept.length) payload.default_kept = kept;
    var text = data.prefix + ' ' + JSON.stringify(payload);
    var out = document.getElementById('out');
    out.value = text; out.style.display = 'block';
    var status = document.getElementById('status');
    function manual(){ out.focus(); out.select(); var ok = false; try { ok = document.execCommand('copy'); } catch (e) {} status.textContent = ok ? T.copied : T.copyFail; }
    if (navigator.clipboard && navigator.clipboard.writeText) {
      navigator.clipboard.writeText(text).then(function(){ status.textContent = T.copied; }, manual);
    } else manual();
  });
})();
`;

function page({ lang, title, body, data }) {
  const csp = "default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; img-src data:";
  return `<!doctype html>
<html lang="${lang === 'en' ? 'en' : 'zh-CN'}">
<head>
<meta charset="utf-8">
<meta http-equiv="Content-Security-Policy" content="${csp}">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="generator" content="codex-plan-ledger">
<title>${escapeHtml(title)}</title>
<style>${CSS}</style>
</head>
<body>
${body}
${data ? `<script type="application/json" id="pl-data">${jsonForScript(data)}</script>\n<script>${SCRIPT}</script>` : ''}
</body>
</html>
`;
}

/** Page for the pass-through case. */
export function renderFailure({ original, reason, lang = 'zh' }) {
  const t = STRINGS[lang] || STRINGS.zh;
  const body = `<main class="fail">
<h1>${escapeHtml(t.failTitle)}</h1>
<p class="banner">${escapeHtml(t.failNote)}</p>
<p class="meta">${escapeHtml(t.failReason)}: ${escapeHtml(reason || 'unknown')}</p>
<pre>${escapeHtml(original ?? '')}</pre>
<footer>${escapeHtml(t.footer)}</footer>
</main>`;
  return page({ lang, title: t.failTitle, body, data: null });
}

function optionLabel(d, id) {
  if (id === 'other') return null;
  const o = d.options.find((x) => x.id === id);
  return o ? o.label : null;
}

/**
 * Render the decision page.
 * @param {object} p
 * @param {object} p.ledger   decisions.json content
 * @param {string} p.planText original plan Markdown
 * @param {object} [p.changes] { added: [id], changed: [{id, fields}], removed: [{id, title}] }
 * @param {string} [p.ledgerPath] repo-relative path shown in the header
 * @param {'zh'|'en'} [p.lang]
 */
export function renderPlanHtml({ ledger, planText, changes = null, ledgerPath = '', lang = 'zh' }) {
  const t = STRINGS[lang] || STRINGS.zh;
  const decisions = ledger.decisions || [];
  const added = new Set(changes?.added || []);
  const changed = new Map((changes?.changed || []).map((c) => [c.id, c.fields]));
  const removed = changes?.removed || [];
  const assumptions = decisions.filter((d) => d.kind === 'assumption').length;

  const parts = [];
  parts.push(`<main>`);
  parts.push(`<h1>${escapeHtml(ledger.title)}</h1>`);
  if (ledger.summary) parts.push(`<p class="summary">${escapeHtml(ledger.summary)}</p>`);
  parts.push(`<p class="meta">${escapeHtml(t.ledger)}: <code>${escapeHtml(ledgerPath || `docs/plans/${ledger.plan_id}/decisions.json`)}</code> · rev ${escapeHtml(ledger.revision)}</p>`);

  if (decisions.length === 0) {
    parts.push(`<p class="count">${escapeHtml(t.none)}</p>`);
  } else {
    const answered = decisions.filter((d) => d.status === 'answered').length;
    parts.push(`<p class="count" id="count">${escapeHtml(t.need(decisions.length))}${assumptions ? escapeHtml(t.needAssume(assumptions)) : ''}${answered ? escapeHtml(t.answeredCount(answered)) : ''}</p>`);
  }
  if (changes && (added.size || changed.size || removed.length)) {
    parts.push(`<p class="banner">${escapeHtml(t.changedBanner(added.size, changed.size, removed.length))}</p>`);
  }

  for (const d of decisions) {
    const cls = added.has(d.id) ? ' is-added' : changed.has(d.id) ? ' is-changed' : '';
    const tags = [`<span class="tag">${escapeHtml(t.kind[d.kind] || d.kind)}</span>`];
    if (added.has(d.id)) tags.push(`<span class="tag added">${escapeHtml(t.added)}</span>`);
    if (changed.has(d.id)) tags.push(`<span class="tag changed">${escapeHtml(t.changed)}: ${escapeHtml(changed.get(d.id).join(', '))}</span>`);
    if (d.status === 'answered') tags.push(`<span class="tag done">${escapeHtml(t.answeredInLedger)}</span>`);
    if (d.status === 'answered' && d.carried) tags.push(`<span class="tag carried">${escapeHtml(t.carried(d.carried.from_revision, d.carried.match))}</span>`);
    const name = `c-${d.id}`;
    const opts = d.options.map((o) => {
      const checked = d.status === 'answered' && d.chosen === o.id ? ' checked' : '';
      const rec = o.recommended ? ` <span class="tag rec">${escapeHtml(t.recommended)}</span>` : '';
      return `<label class="opt"><input type="radio" name="${escapeHtml(name)}" value="${escapeHtml(o.id)}"${checked}><span>${inline(o.label)}${rec}</span></label>`;
    });
    const otherChecked = d.status === 'answered' && d.chosen === 'other' ? ' checked' : '';
    opts.push(`<label class="opt"><input type="radio" name="${escapeHtml(name)}" value="other"${otherChecked}><span>${escapeHtml(t.other)}<input class="other-text" type="text" placeholder="${escapeHtml(t.otherPh)}" value="${escapeHtml(d.chosen === 'other' ? d.other || '' : '')}"></span></label>`);
    const defLabel = optionLabel(d, d.default);
    const def = defLabel ? `${t.defaultIs}: ${defLabel}` : t.noDefault;
    const files = [...(d.affected?.files || []), ...(d.affected?.modules || [])];
    parts.push(`<section class="card${cls}" data-id="${escapeHtml(d.id)}">
<div>${tags.join('')}<span class="tag">${escapeHtml(d.id)}</span></div>
<h2>${inline(d.title)}</h2>
${d.question && d.question !== d.title ? `<p class="q">${inline(d.question)}</p>` : ''}
${opts.join('\n')}
<textarea class="why" placeholder="${escapeHtml(t.whyPh)}">${escapeHtml(d.rationale || '')}</textarea>
<div class="def">${escapeHtml(def)} · ${escapeHtml(t.notAnswered)}</div>
${files.length ? `<div class="files">${escapeHtml(t.affected)}: ${files.map((f) => `<code>${escapeHtml(f)}</code>`).join('')}</div>` : ''}
</section>`);
  }
  if (removed.length) {
    parts.push(`<p class="removed">${escapeHtml(t.removed)}: ${removed.map((r) => `<code>${escapeHtml(r.id)}</code> ${escapeHtml(r.title)}`).join(' · ')}</p>`);
  }
  const earlier = ledger.earlier_answers || [];
  if (earlier.length) {
    parts.push(`<section class="earlier"><h2>${escapeHtml(t.earlierTitle)}</h2><p class="hint">${escapeHtml(t.earlierNote)}</p><ul>${earlier.map((e) => `<li><strong>${inline(e.title)}</strong>: ${escapeHtml(e.chosen === 'other' ? e.other || '' : e.chosen_label || e.chosen || '')} <span class="meta">(rev ${escapeHtml(e.from_revision)} · ${escapeHtml(t.reasonText[e.reason] || e.reason)})</span></li>`).join('')}</ul></section>`);
  }
  parts.push(`<details><summary>${escapeHtml(t.fullPlan)}</summary>\n${markdownToHtml(planText || '')}\n</details>`);
  parts.push(`<footer>${escapeHtml(t.footer)}</footer>`);
  parts.push(`</main>`);
  if (decisions.length) {
    parts.push(`<div class="bar"><div class="bar-in">
<div class="row"><button id="build" type="button">${escapeHtml(t.button)}</button><span class="hint">${escapeHtml(t.hint)}</span><span id="status" role="status"></span></div>
<div class="hint" id="progress"></div>
<textarea id="out" readonly></textarea>
</div></div>`);
  }
  const data = decisions.length
    ? {
        plan: ledger.plan_id,
        rev: ledger.revision,
        prefix: ANSWER_PREFIX,
        t: { progress: t.progress('{k}', '{n}'), copied: t.copied, copyFail: t.copyFail },
      }
    : null;
  return page({ lang, title: ledger.title, body: parts.join('\n'), data });
}
